name: Build adb-fastboot

on:
  push:
    branches:
      - main
    paths-ignore:
      - get_sources.sh
      - README.md
      - .github/**
      - patches/*
      - tools/*
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Reason'     
        required: false
        default: 'Update package'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target_abi: [arm64-v8a, armeabi-v7a, x86_64, x86]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'false'

      - name: Prerequisites
        run: |
            sudo apt install \
            ninja-build \
            autogen \
            autoconf \
            libtool \
            build-essential \
            -y

      - name: Download tools
        run: |
            CLEANER=tools/termux-elf-cleaner
            CLEANER_VERSION=v2.1.1
            CLEANER_URL="https://github.com/termux/termux-elf-cleaner/releases/download/${CLEANER_VERSION}/termux-elf-cleaner"
            # remove old and download new
            rm $CLEANER
            curl -L  $CLEANER_URL > $CLEANER
            chmod +x $CLEANER
        
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r24
          add-to-path: false
      - run: bash build.sh ${{ matrix.target_abi }}
        env:
          NDK_PATH: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: adb-fastboot-${{ matrix.target_abi }}
          path: output/${{ matrix.target_abi }}