name: Build adb

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - .github/**
      - patches/*
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Reason'     
        required: false
        default: 'Update package'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target_abi: [arm64-v8a, armeabi-v7a, x86_64, x86]
      fail-fast: false
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Prerequisites
        run: |
          sudo apt install \
          ninja-build \
          autogen \
          autoconf \
          libtool \
          build-essential \
          cmake \
          curl \
          -y

      - name: Setup cleaner
        run: |
            cleaner_version=v2.1.1
            curl -L https://github.com/termux/termux-elf-cleaner/releases/download/${cleaner_version}/termux-elf-cleaner > /usr/local/bin/termux-elf-cleaner
            chmod +x /usr/local/bin/termux-elf-cleaner
        
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r25b
          add-to-path: false
      - run: bash build.sh ${{ matrix.target_abi }}
        env:
          NDK: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: adb-${{ matrix.target_abi }}
          path: build/bin